_OUI_DB = {
    'D8EB97': ('tp-link',    'TP-Link'),
    'F4F26D': ('tp-link',    'TP-Link'),
    'B0487A': ('tp-link',    'TP-Link'),
    '4C1FCC': ('tp-link',    'TP-Link'),
    'A0F3C1': ('tp-link',    'TP-Link'),
    '50FA84': ('tp-link',    'TP-Link'),
    '18D6C7': ('tp-link',    'TP-Link'),
    '8C8D28': ('tp-link',    'TP-Link'),
    '98DED0': ('tp-link',    'TP-Link'),
    'C4E984': ('tp-link',    'TP-Link'),
    '1040F3': ('tp-link',    'TP-Link'),
    'E8DE27': ('tp-link',    'TP-Link'),
    '5C628B': ('tp-link',    'TP-Link'),
    '60E3270':('tp-link',    'TP-Link'),
    '2C4D54': ('netgear',    'Netgear'),
    '287491': ('netgear',    'Netgear'),
    '9C3DCF': ('netgear',    'Netgear'),
    'A021B7': ('netgear',    'Netgear'),
    'C03F0E': ('netgear',    'Netgear'),
    '103498': ('netgear',    'Netgear'),
    '20E52A': ('netgear',    'Netgear'),
    '6CB0CE': ('netgear',    'Netgear'),
    'E091F5': ('netgear',    'Netgear'),
    '4C60DE': ('netgear',    'Netgear'),
    'C4048A': ('huawei',     'Huawei'),
    '1C1D67': ('huawei',     'Huawei'),
    '485A3F': ('huawei',     'Huawei'),
    'D0271C': ('huawei',     'Huawei'),
    'F48E38': ('huawei',     'Huawei'),
    '346987': ('huawei',     'Huawei'),
    '98E7F4': ('huawei',     'Huawei'),
    'A0A33B': ('huawei',     'Huawei'),
    '24DF6A': ('huawei',     'Huawei'),
    '5488DC': ('huawei',     'Huawei'),
    'AC853D': ('huawei',     'Huawei'),
    '70723C': ('huawei',     'Huawei'),
    '5C4CEB': ('asus',       'ASUS'),
    '2C4D4F': ('asus',       'ASUS'),
    '107B44': ('asus',       'ASUS'),
    'AC9E17': ('asus',       'ASUS'),
    'F832E4': ('asus',       'ASUS'),
    '0050FC': ('asus',       'ASUS'),
    '3C7A8A': ('asus',       'ASUS'),
    '04D9F5': ('asus',       'ASUS'),
    '08606E': ('asus',       'ASUS'),
    'E03F49': ('asus',       'ASUS'),
    '1C872C': ('linksys',    'Linksys/Cisco'),
    'C08400': ('linksys',    'Linksys/Cisco'),
    '20AA4B': ('linksys',    'Linksys/Cisco'),
    'E8FC4F': ('linksys',    'Linksys/Cisco'),
    '14C113': ('linksys',    'Linksys/Cisco'),
    '6895F9': ('linksys',    'Linksys/Cisco'),
    'BC1401': ('linksys',    'Linksys/Cisco'),
    '10BEF5': ('linksys',    'Linksys/Cisco'),
    '30485A': ('mikrotik',   'MikroTik'),
    '4C5E0C': ('mikrotik',   'MikroTik'),
    'E48D8C': ('mikrotik',   'MikroTik'),
    '6C3B6B': ('mikrotik',   'MikroTik'),
    '18FD74': ('mikrotik',   'MikroTik'),
    'B8690A': ('mikrotik',   'MikroTik'),
    '2C3A28': ('dlink',      'D-Link'),
    '7C8BCA': ('dlink',      'D-Link'),
    '9094E4': ('dlink',      'D-Link'),
    '001B11': ('dlink',      'D-Link'),
    '14D64D': ('dlink',      'D-Link'),
    '84C9B2': ('dlink',      'D-Link'),
    '1CAFF7': ('dlink',      'D-Link'),
    '28107B': ('dlink',      'D-Link'),
    'CCBE59': ('dlink',      'D-Link'),
    'F07D68': ('dlink',      'D-Link'),
    '60D819': ('aruba',      'Aruba/HP'),
    '9C1C12': ('aruba',      'Aruba/HP'),
    '20A6CD': ('aruba',      'Aruba/HP'),
    '24DE C6':('aruba',      'Aruba/HP'),
    '94B40F': ('aruba',      'Aruba/HP'),
    '000B86': ('aruba',      'Aruba/HP'),
    '20400C': ('ubiquiti',   'Ubiquiti'),
    '04188D': ('ubiquiti',   'Ubiquiti'),
    '78D29B': ('ubiquiti',   'Ubiquiti'),
    'B4FBE4': ('ubiquiti',   'Ubiquiti'),
    'E063DA': ('ubiquiti',   'Ubiquiti'),
    'F09FC2': ('ubiquiti',   'Ubiquiti'),
    '804BF1': ('ubiquiti',   'Ubiquiti'),
    '68722D': ('ubiquiti',   'Ubiquiti'),
    '241A8C': ('ubiquiti',   'Ubiquiti'),
    'FCECDA': ('ubiquiti',   'Ubiquiti'),
    '74ACB9': ('zte',        'ZTE'),
    'BC3DBA': ('zte',        'ZTE'),
    'B0E5ED': ('zte',        'ZTE'),
    '502636': ('zte',        'ZTE'),
    '44A5CE': ('zte',        'ZTE'),
    'FC4A93': ('zte',        'ZTE'),
    'A8F94B': ('zte',        'ZTE'),
    '703A51': ('zte',        'ZTE'),
    '9440B6': ('zte',        'ZTE'),
    'C864C7': ('zte',        'ZTE'),
    '5035AF': ('motorola',   'Motorola/Arris'),
    'AC3BA7': ('arris',      'Arris'),
    '001393': ('arris',      'Arris'),
    '000F21': ('arris',      'Arris'),
    '40C736': ('arris',      'Arris'),
    '005056': ('vmware',     'VMware'),
    '0003FF': ('microsoft',  'Microsoft'),
    '8CFE74': ('tenda',      'Tenda'),
    'C8D3A3': ('tenda',      'Tenda'),
    'B098BC': ('tenda',      'Tenda'),
    '00B5F3': ('tenda',      'Tenda'),
    'C83A35': ('tenda',      'Tenda'),
    '889FFD': ('mercusys',   'Mercusys'),
    '80EA96': ('mercusys',   'Mercusys'),
    '6C5AB0': ('mercusys',   'Mercusys'),
    '3C84FF': ('ubee',       'Ubee/Ambit'),
    'A85BD9': ('ubee',       'Ubee/Ambit'),
    '48EE0C': ('technicolor','Technicolor'),
    'C8E86D': ('technicolor','Technicolor'),
    '20FA85': ('technicolor','Technicolor'),
    '00248C': ('technicolor','Technicolor'),
}


def lookup(bssid):
    clean = bssid.replace(':', '').replace('-', '').upper()
    oui   = clean[:6]
    entry = _OUI_DB.get(oui)
    if entry:
        return entry
    for prefix_len in (5, 4):
        entry = _OUI_DB.get(oui[:prefix_len])
        if entry:
            return entry
    return (None, 'Unknown')


def vendor_key(bssid):
    key, _ = lookup(bssid)
    return key


def vendor_name(bssid):
    _, name = lookup(bssid)
    return name
